#spring:
#  datasource:
#    url: jdbc:h2:mem:APP_USERS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
#    username: sa
#    password:
#server:
#  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cd
    username: ubuntu
    password: ubuntu
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 9095
